image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

  CI_DOCKER_COMPOSE_SERVICE_NAME: ams
  CI_REGISTRY_IMAGE: project/ams/$CI_DOCKER_COMPOSE_SERVICE_NAME
  GIT_DEPTH: "3"

stages:
  - deploy-dev 

deploy-dev:
  stage: deploy-dev  
  image: alpine:latest
  
  tags:
    - dev
  only:
    - dev
  before_script:
    - apk --no-cache add ca-certificates
    - apk add --no-cache rsync
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo -e "$DS0_RSA_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
  script:
    - ssh -p $DEV_SERVER_SSH_PORT ds3@$DEV_SERVER_HOST "cd $DEV_SOURCE_PATH; git pull; git checkout dev; git pull;  docker build --pull -t "$CI_REGISTRY/$CI_REGISTRY_IMAGE:latest" -f Dockerfile .; docker service update --image $CI_REGISTRY/$CI_REGISTRY_IMAGE:latest --with-registry-auth --force '${DEV_DOCKER_STACK_NAME}_${CI_DOCKER_COMPOSE_SERVICE_NAME}'"

